build:
  maxIssues: 0

complexity:
  active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 10
    ignoreAnnotatedFunctions: ['Preview']
  LongMethod:
    active: true
    threshold: 40
    ignoreAnnotated: ['Composable']

  LongParameterList:
    active: true
    functionThreshold: 5
    constructorThreshold: 20
    ignoreDataClasses: true
    ignoreAnnotated: ['Composable']

style:
  active: true
  MagicNumber:
    active: false

  ForbiddenComment:
    active: true

  NewLineAtEndOfFile:
    active: false

  MaxLineLength:
    active: true
    maxLineLength: 200

  UnnecessaryApply:
    active: true

  UnnecessaryLet:
    active: true

  UnusedPrivateMember:
    active: true
    ignoreAnnotated: ['Preview']

  VarCouldBeVal:
    active: true

potential-bugs:
  active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true

  UnnecessarySafeCall:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true

  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true

naming:
  active: true
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'

  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
    ignoreAnnotated: ['Composable']
    excludes: ['**/test/**']

  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'

coroutines:
  active: true
  RedundantSuspendModifier:
    active: true

  SleepInsteadOfDelay:
    active: true